### ISSUE TITLE
libritts: AssertionError: No recordings left after fixing the manifests.

### ISSUE THREAD

**Issue by Yixing-Li** [lifeiteng/valle#192]
When I'm preparing datasets of libritts, I run into this issue:

`Scanning audio files (*.wav): 0it [00:00, ?it/s]
Preparing LibriTTS parts:  71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                           | 5/7 [00:00<00:00, 2690.38it/s]
Traceback (most recent call last):
  File "/data/workspace/anaconda/anaconda3/envs/valle/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/lhotse/bin/modes/recipes/libritts.py", line 49, in libritts                                                                                                                                
    prepare_libritts(
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/lhotse/recipes/libritts.py", line 279, in prepare_libritts                                                                                                                                 
    recordings, supervisions = fix_manifests(recordings, supervisions)
  File "/data/workspace/anaconda/anaconda3/envs/valle/lib/python3.8/site-packages/lhotse/qa.py", line 65, in fix_manifests
    assert (
AssertionError: No recordings left after fixing the manifests.`

I've searched up for this kind of issue and I found a similar one:
https://github.com/lhotse-speech/lhotse/issues/989

Seems that downloading libritts with lhotse would cause similar problem. Anyone got similar issue? Thx!

**Comment by YJCmote1** [comment]
Sorry, may I ask if you have fixed the issue?
